[package]
name = "bktrk"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
proptest = "1.0.0"
proptest-derive = "0.3.0"

[[bench]]
harness = false
name = "rect_gen_benchmark"

[dependencies]
itertools = "0.10.3"
